using System.Reflection;
using System.IO;
using IPhoneMirror.App.Services;
var bridge = new DirectUsbInputBridge();
var flags = BindingFlags.Instance | BindingFlags.NonPublic;
typeof(DirectUsbInputBridge).GetField("_requestedUdid", flags)!.SetValue(bridge, "device-test");
var line = typeof(DirectUsbInputBridge).GetMethod("HandleLine", flags)!;
void Emit(string json) => line.Invoke(bridge, [json]);
void Assert(bool condition, string label) { if (!condition) throw new Exception(label); Console.WriteLine("PASS " + label); }
const string ready = """{"event":"ready","udid":"device-test","transport":"usb","rateHz":120,"gateOpen":true,"authMode":"direct"}""";
Emit(ready); Assert(bridge.IsReady, "initial validated readiness");
Emit(ready.Replace("device-test", "wrong-device"));
Assert(!bridge.IsReady && !bridge.GateOpen, "mismatched replacement ready closes stale input gate");
Emit(ready);
Emit(ready.Replace("\"usb\"", "\"wireless\""));
Assert(!bridge.IsReady && !bridge.GateOpen, "wrong transport ready closes stale input gate");
Emit(ready);
Emit("""{"event":"status","code":"terminated"}""");
Assert(!bridge.IsReady && !bridge.GateOpen, "termination closes readiness and authentication gate");
Emit(ready);
Emit("""{"event":"status","code":"recovery_triggered","message":"socket lost"}""");
Assert(!bridge.IsReady && !bridge.GateOpen, "recovery closes input gate");
try { await bridge.SendKeyboardAsync([]); throw new Exception("send was allowed during recovery"); }
catch (InvalidOperationException) { Console.WriteLine("PASS input rejected during recovery"); }
Emit(ready); Assert(bridge.IsReady && bridge.GateOpen, "new ready restores input gate");
Emit("""{"event":"error","code":"direct_hid_recovery_exhausted","message":"failed"}""");
Assert(!bridge.IsReady && !bridge.GateOpen, "exhaustion cannot remain ready");
Emit(ready); Assert(bridge.IsReady && bridge.LastErrorCode is null, "new generation clears terminal error");
var hostType=typeof(DirectUsbInputBridge).Assembly.GetType("IPhoneMirror.App.Services.UsbTouchBridgeHost")!;
var host=Activator.CreateInstance(hostType, true)!;
var onEvent=hostType.GetMethod("OnBridgeEvent",flags)!;
string State() => hostType.GetProperty("State",flags)!.GetValue(host)!.ToString()!;
onEvent.Invoke(host,[new BridgeEvent("status","recovery_triggered",null)]);
Assert(State()=="Recovering","host tracks recovery");
onEvent.Invoke(host,[new BridgeEvent("ready",null,null)]);
Assert(State()=="Ready","host sender accepts replacement ready");
onEvent.Invoke(host,[new BridgeEvent("error","bridge_exited",null)]);
Assert(State()=="Error","host detects process failure");
var queuedBridge=(DirectUsbInputBridge)hostType.GetField("_bridge",flags)!.GetValue(host)!;
typeof(DirectUsbInputBridge).GetField("_requestedUdid",flags)!.SetValue(queuedBridge,"device-test");
line.Invoke(queuedBridge,[ready]);
onEvent.Invoke(host,[new BridgeEvent("ready",null,null)]);
using var bytes=new MemoryStream();
typeof(DirectUsbInputBridge).GetField("_stdin",flags)!.SetValue(queuedBridge,new StreamWriter(bytes));
var writerGate=(SemaphoreSlim)typeof(DirectUsbInputBridge).GetField("_sendLock",flags)!.GetValue(queuedBridge)!;
var vmType=typeof(DirectUsbInputBridge).Assembly.GetType("IPhoneMirror.App.ViewModels.MainViewModel")!;
var vm=System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(vmType);
var controlType=typeof(DirectUsbInputBridge).Assembly.GetType("IPhoneMirror.App.Services.DeviceControlSession")!;
var control=Activator.CreateInstance(controlType,BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic,null,["device-test"],null)!;
foreach(var (name,value) in new (string,object)[]{("WiredEnabled",true),("WiredConnected",true),("WiredTarget","device-test"),("WiredBridge",host)})
    controlType.GetField(name,flags)!.SetValue(control,value);
var controlsType=typeof(Dictionary<,>).MakeGenericType(typeof(string),controlType);
var controls=(System.Collections.IDictionary)Activator.CreateInstance(controlsType)!;
controls.Add("device-test",control);
vmType.GetField("_deviceControls",flags)!.SetValue(vm,controls);
await writerGate.WaitAsync();
var queuedSend=(Task)vmType.GetMethod("SendUsbTouchAsync",flags)!.Invoke(vm,["down",0.5,0.5,"device-test",CancellationToken.None])!;
Assert(!queuedSend.IsCompleted,"touch waits for occupied writer");
line.Invoke(queuedBridge,["""{"event":"status","code":"recovery_triggered"}"""]);
writerGate.Release();
await queuedSend;
Assert(bytes.Length==0,"recovery safely drops queued touch without an unobserved failure");
line.Invoke(queuedBridge,[ready.Replace("\"rateHz\":120", "\"rateHz\":120,\"generation\":1")]);
await writerGate.WaitAsync();
var oldPress=queuedBridge.SendKeyboardAsync(new byte[]{4});
line.Invoke(queuedBridge,["""{"event":"status","code":"recovery_triggered"}"""]);
line.Invoke(queuedBridge,[ready.Replace("\"rateHz\":120", "\"rateHz\":120,\"generation\":2")]);
writerGate.Release();
await oldPress;
Assert(bytes.Length==0,"queued old press is dropped even when recovery finished before writer resumes");
await queuedBridge.DisposeAsync();
await bridge.DisposeAsync();
Console.WriteLine("USB recovery lifecycle tests passed.");
